### ISSUE TITLE
fix compilation errors when switching to RxCPP 4.0

### ISSUE THREAD

**Issue by d-led** [d-led/influxdb-cpp-rest#5]
when switching to RxCPP 4.0, the RxCPP part does not compile anymore with the same assertion on [Linux](https://travis-ci.org/d-led/influxdb-cpp-rest/builds/241365053) and Windows (update via nuget):

```
rx-observable.hpp:537:9: error: static assertion failed: inner must have on_subscribe method
that accepts this subscriber
```

@kirkshoop any hints? I'm somewhat out of ideas. A similar example in a small project [rxcpp_operators](https://github.com/d-led/rxcpp_operators) does not have that problem

**Comment by kirkshoop** [comment]
Hi!

Regarding this assert.

```
../../../src/influxdb-cpp-rest/influxdb_simple_async_api.cpp:54:108:   required from here
../../../deps/rxcpp/Rx/v2/src/rxcpp/operators/rx-window_time_count.hpp:275:9: error: static assertion failed: window_with_time_or_count takes (Duration, Count, optional Coordination)
         static_assert(sizeof...(AN) == 10000, "window_with_time_or_count takes 
```

from this line

```
            listener = incoming_requests
                .window_with_time_or_count(window_max_ms, window_max_lines, rxcpp::synchronize_new_thread())
```

the issue seems to be that the work to support rx-lite has changed the overload resolution for `window_with_time_or_count`.

I think that the duration and scheduler arguments are fine, but the count parameter is expected to be signed int (see [here](https://github.com/Reactive-Extensions/RxCpp/blob/master/Rx/v2/src/rxcpp/operators/rx-window_time_count.hpp#L266)), but `window_max_lines` is unsigned int. 

`rxcpp_operators` works because `100000` is an int literal, which matches.

**Comment by d-led** [comment]
Hi! Thanks! Good to know! Let's see if it works. Compiled in VS ok

**Comment by d-led** [comment]
@kirkshoop compiles ok!
